name: "Test"
test: #TODO to remove
  input-topic: "quickstart-events"
  output-topic: "output-topic"
  test-topic: "test-topic"
app:
  kafka:
    application-name: "job-data-analyzer"
    bootstrap-server: "localhost:9092"

spring:
  kafka:
    bootstrap-servers: "localhost:9092"
    consumer:
      group-id: "my-group"
      auto-offset-reset: "earliest"
    template:
      default-topic: "my-topic"